# See https://github.com/HathHub/PlayerStats
MySQL:
    ConnectionString: "Server=localhost;Port=3306;Database=dbname;User=username;Password=password;"
    TableName: "HathPlayerStats"

Messages:
  Stats: "[Stats for {PlayerName} #{Position}]\n Kills: {Kills} Deaths: {Deaths} Headshots: {Headshots} Accuracy: {Accuracy}\n Messages: {Messages} Zombies: {Zombies} Megas: {MegaZombies}\nFish: {Fish} Animals: {Animals} Harvests: {Harvests} Resources: {Resources}"
  RankingHeader: "<b>[Top 5 players]</b>"
  Ranking: "#{Position} {PlayerName}: Kills: {Kills} Deaths: {Deaths} Headshots: {Headshots} Accuracy: {Accuracy}"

Ranking:
  SortBy: "Kills"
  Limit: "5"

Discord:
  Enabled: true
  Interval: 60
  Embeds:
    - MyKillsEmbed:
      Top: 3
      SortBy: "Kills"
      Webhook: ""      
      MessageID: 214124531553
      Header: "asd"
      Description: "asd"
      Field:
        Inline: true
        Name: "🥇**#{Position}**"
        Value: "👤 **[{PlayerName}](https://steamcommunity.com/profiles/{SteamID})**
                > 🪦 **{Kills}** Kills"
    - MyHeadshotsEmbed:
      Top: 3
      SortBy: "Headshots"
      Webhook: ""      
      MessageID: 214124531553
      Header: "asd"
      Description: "asd"
      Field:
        Inline: true
        Name: "🥇**#{Position}**"
        Value: "👤 **[{PlayerName}](https://steamcommunity.com/profiles/{SteamID})**
                > 💀 **{Headshots}** Headshots"

Rewards:
  - Variable: "Kills"
    Threshold: 100
    Commands:
      - "give {PlayerID} 363"
      - "give {PlayerID} 17"
    Global: false
    Messages:
      - "Congratulations! You've reached 100 kills and earned a Maplestrike and Drum."

  - Variable: "Headshots"
    Threshold: 50
    Commands:
      - "give {PlayerID} 363"
      - "give {PlayerID} 17"
    Global: true
    Messages:
      - "Sharpshooter Alert! {PlayerName} achieved 50 headshots and earned a Maplestrike. Everyone, cheer!"